from __future__ import annotations

from .core import ZCATProblem
from .instances import (
    ZCAT1Problem,
    ZCAT2Problem,
    ZCAT3Problem,
    ZCAT4Problem,
    ZCAT5Problem,
    ZCAT6Problem,
    ZCAT7Problem,
    ZCAT8Problem,
    ZCAT9Problem,
    ZCAT10Problem,
    ZCAT11Problem,
    ZCAT12Problem,
    ZCAT13Problem,
    ZCAT14Problem,
    ZCAT15Problem,
    ZCAT16Problem,
    ZCAT17Problem,
    ZCAT18Problem,
    ZCAT19Problem,
    ZCAT20Problem,
)

__all__ = [
    "ZCATProblem",
    "ZCAT1Problem",
    "ZCAT2Problem",
    "ZCAT3Problem",
    "ZCAT4Problem",
    "ZCAT5Problem",
    "ZCAT6Problem",
    "ZCAT7Problem",
    "ZCAT8Problem",
    "ZCAT9Problem",
    "ZCAT10Problem",
    "ZCAT11Problem",
    "ZCAT12Problem",
    "ZCAT13Problem",
    "ZCAT14Problem",
    "ZCAT15Problem",
    "ZCAT16Problem",
    "ZCAT17Problem",
    "ZCAT18Problem",
    "ZCAT19Problem",
    "ZCAT20Problem",
]
