from __future__ import annotations


def parse_bounds_text(text: str, n_var: int) -> list[tuple[float, float]] | str:
    """Parse a bounds textarea into a list of (lo, hi) tuples."""
    lines = [ln.strip() for ln in text.strip().splitlines() if ln.strip()]
    if len(lines) == 1:
        parts = lines[0].replace("(", "").replace(")", "").split(",")
        if len(parts) != 2:
            return "Enter two comma-separated numbers, e.g.  0.0, 1.0"
        try:
            lo, hi = float(parts[0].strip()), float(parts[1].strip())
        except ValueError:
            return "Bounds must be numbers."
        if lo > hi:
            return f"Lower bound ({lo}) must be <= upper bound ({hi})."
        return [(lo, hi)] * n_var

    if len(lines) != n_var:
        return f"Expected 1 line (same for all) or {n_var} lines (one per variable), got {len(lines)}."
    result: list[tuple[float, float]] = []
    for i, line in enumerate(lines):
        parts = line.replace("(", "").replace(")", "").split(",")
        if len(parts) != 2:
            return f"Line {i + 1}: expected two comma-separated numbers."
        try:
            lo, hi = float(parts[0].strip()), float(parts[1].strip())
        except ValueError:
            return f"Line {i + 1}: bounds must be numbers."
        if lo > hi:
            return f"Line {i + 1}: lower ({lo}) > upper ({hi})."
        result.append((lo, hi))
    return result


def generate_script(
    code: str,
    *,
    name: str,
    n_var: int,
    n_obj: int,
    bounds: list[tuple[float, float]],
    algorithm: str,
    budget: int,
    constraint_code: str = "",
    n_constraints: int = 0,
) -> str:
    """Generate a standalone Python script from the builder state."""
    func_name = "".join(c if c.isalnum() else "_" for c in name.lower()).strip("_") or "custom"
    while "__" in func_name:
        func_name = func_name.replace("__", "_")

    has_constraints = bool(constraint_code.strip()) and n_constraints > 0

    parts: list[str] = [
        '"""',
        f"Custom problem: {name}",
        "",
        "Generated by VAMOS Studio -- Problem Builder.",
        '"""',
        "",
        "from vamos import make_problem, optimize",
        "",
        "",
        f"def {func_name}(x):",
        f'    """Evaluate one solution (x has length {n_var}). Returns {n_obj} objectives."""',
    ]
    for ln in code.splitlines():
        parts.append(f"    {ln}")

    if has_constraints:
        parts += [
            "",
            "",
            f"def {func_name}_constraints(x):",
            '    """Constraint function. Values <= 0 are feasible."""',
        ]
        for ln in constraint_code.splitlines():
            parts.append(f"    {ln}")

    parts += ["", "", "problem = make_problem(", f"    {func_name},"]
    parts.append(f"    n_var={n_var},")
    parts.append(f"    n_obj={n_obj},")
    parts.append(f"    bounds={bounds!r},")
    parts.append('    encoding="real",')
    parts.append(f'    name="{name}",')
    if has_constraints:
        parts.append(f"    constraints={func_name}_constraints,")
        parts.append(f"    n_constraints={n_constraints},")
    parts.append(")")

    parts += [
        "",
        'if __name__ == "__main__":',
        "    result = optimize(",
        "        problem,",
        f'        algorithm="{algorithm}",',
        f"        max_evaluations={budget},",
        "        seed=42,",
        "        verbose=True,",
        "    )",
        "    F = result.F",
        '    print(f"\\nFound {len(F)} non-dominated solutions")',
    ]
    for i in range(n_obj):
        parts.append(f'    print(f"  f{i}: [{{F[:, {i}].min():.4f}}, {{F[:, {i}].max():.4f}}]")')
    parts.append("")

    return "\n".join(parts)


__all__ = ["generate_script", "parse_bounds_text"]
