from __future__ import annotations

import json
import shutil
from functools import lru_cache
from pathlib import Path

from vamos.engine.config.spec import validate_experiment_spec
from vamos.experiment.cli.args import build_parser, build_pre_parser
from vamos.experiment.cli.loaders import load_spec_defaults
from vamos.experiment.cli.spec_args import parser_spec_keys
from vamos.foundation.core.experiment_config import ExperimentConfig

_REQUIRED_PLAN_FILES: tuple[str, ...] = ("config.json", "plan.json")
_OPTIONAL_PLAN_FILES: tuple[str, ...] = ("prompt.txt", "catalog.json")

_README_CONTENT = """# Run VAMOS

This directory was generated by `vamos assist apply`.

## How To Run

```bash
vamos --config config.json
python -m vamos.experiment.cli.main --config config.json
```

Results/output location is controlled by fields in `config.json` (for example `defaults.output_root`).
"""


@lru_cache(maxsize=1)
def _spec_allowed_overrides() -> tuple[str, ...]:
    default_config = ExperimentConfig()
    pre_parser = build_pre_parser()
    spec_defaults = load_spec_defaults(None)
    parser = build_parser(default_config=default_config, pre_parser=pre_parser, spec_defaults=spec_defaults)
    return tuple(sorted(parser_spec_keys(parser)))


def _read_json(path: Path) -> object:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise ValueError(f"Invalid JSON file: {path.name}") from exc


def _validate_plan_dir(plan_dir: Path) -> None:
    if not plan_dir.exists() or not plan_dir.is_dir():
        raise ValueError(f"Plan directory not found: {plan_dir}")
    for name in _REQUIRED_PLAN_FILES:
        if not (plan_dir / name).is_file():
            raise ValueError(f"Missing required plan file: {name}")


def _validate_config(config_data: object) -> None:
    try:
        validate_experiment_spec(config_data, allowed_overrides=_spec_allowed_overrides())
    except Exception as exc:
        raise ValueError(f"Invalid plan config: {exc}") from exc


def _prepare_project_dir(project_dir: Path, *, overwrite: bool) -> None:
    if project_dir.exists():
        if not overwrite:
            raise ValueError(f"Project directory already exists: {project_dir}")
        shutil.rmtree(project_dir)
    project_dir.mkdir(parents=True, exist_ok=False)


def _copy_plan_files(plan_dir: Path, project_dir: Path) -> None:
    for name in (*_REQUIRED_PLAN_FILES, *_OPTIONAL_PLAN_FILES):
        src = plan_dir / name
        if src.is_file():
            shutil.copy2(src, project_dir / name)


def apply_plan(plan_dir: Path, out_dir: Path | None = None, overwrite: bool = False) -> Path:
    resolved_plan_dir = Path(plan_dir)
    _validate_plan_dir(resolved_plan_dir)

    config_data = _read_json(resolved_plan_dir / "config.json")
    _validate_config(config_data)

    project_dir = Path(out_dir) if out_dir is not None else resolved_plan_dir / "project"
    _prepare_project_dir(project_dir, overwrite=overwrite)
    _copy_plan_files(resolved_plan_dir, project_dir)
    (project_dir / "README_run.md").write_text(_README_CONTENT, encoding="utf-8")
    return project_dir


__all__ = ["apply_plan"]
