"""
VAMOS public API.

The symbols exported here are stable for end users. For advanced or
experimental work, import directly from the layered packages:
`vamos.foundation.*`, `vamos.engine.*`, `vamos.experiment.*`, `vamos.ux.*`.
"""

from .api import (
    ExperimentConfig,
    ObjectiveReductionConfig,
    ObjectiveReducer,
    OptimizeConfig,
    OptimizationResult,
    available_problem_names,
    make_problem_selection,
    optimize,
    run_optimization,
    run_self_check,
    reduce_objectives,
)
from .algorithms import (
    IBEA,
    IBEAConfig,
    IBEAConfigData,
    MOEAD,
    MOEADConfig,
    MOEADConfigData,
    NSGAII,
    NSGAIIConfig,
    NSGAIIConfigData,
    NSGAIII,
    NSGAIIIConfig,
    NSGAIIIConfigData,
    SMPSO,
    SMPSOConfig,
    SMPSOConfigData,
    SMSEMOA,
    SMSEMOAConfig,
    SMSEMOAConfigData,
    SPEA2,
    SPEA2Config,
    SPEA2ConfigData,
    available_algorithms,
    resolve_algorithm,
)
from .mcdm import (
    MCDMResult,
    knee_point_scores,
    reference_point_scores,
    tchebycheff_scores,
    weighted_sum_scores,
)
from .plotting import plot_hv_convergence, plot_parallel_coordinates, plot_pareto_front_2d, plot_pareto_front_3d
from .problems import (
    DTLZ1,
    DTLZ2,
    DTLZ3,
    DTLZ4,
    FeatureSelectionProblem,
    HyperparameterTuningProblem,
    ProblemSelection,
    ProblemSpec,
    WeldedBeamDesignProblem,
    WFG1,
    WFG2,
    WFG3,
    WFG4,
    WFG5,
    WFG6,
    WFG7,
    WFG8,
    WFG9,
    ZDT1,
    ZDT2,
    ZDT3,
    ZDT4,
    ZDT6,
    get_problem_names,
)
from .stats import (
    FriedmanResult,
    WilcoxonResult,
    compute_ranks,
    friedman_test,
    pairwise_wilcoxon,
    plot_critical_distance,
)
from .tuning import (
    AlgorithmConfigSpace,
    RandomSearchTuner,
    RacingTuner,
    ParamSpace,
    Real,
    Int,
    Categorical,
    Condition,
    TuningTask,
    EvalContext,
    Instance,
    Scenario,
    build_ibea_config_space,
    build_moead_config_space,
    build_nsgaiii_config_space,
    build_nsgaii_config_space,
    build_smpso_config_space,
    build_smsemoa_config_space,
    build_spea2_config_space,
    config_from_assignment,
)

# Quick-start API for one-liner experiments
from .quick import (
    QuickResult,
    run,
    run_moead,
    run_nsgaii,
    run_nsgaiii,
    run_smsemoa,
    run_spea2,
)

# Exception hierarchy
from .exceptions import (
    ConfigurationError,
    InvalidAlgorithmError,
    InvalidEngineError,
    InvalidOperatorError,
    MissingConfigError,
    ProblemError,
    InvalidProblemError,
    ProblemDimensionError,
    BoundsError,
    OptimizationError,
    ConvergenceError,
    EvaluationError,
    ConstraintViolationError,
    DataError,
    ResultsNotFoundError,
    InvalidResultsError,
    DependencyError,
    BackendNotAvailableError,
)

# Experiment context manager
from .experiment_context import (
    Experiment,
    experiment,
    RunRecord,
    ExperimentSummary,
)

__all__ = [
    # Quick-start API (one-liners)
    "run",
    "run_nsgaii",
    "run_moead",
    "run_spea2",
    "run_smsemoa",
    "run_nsgaiii",
    "QuickResult",
    # Experiment context
    "Experiment",
    "experiment",
    "RunRecord",
    "ExperimentSummary",
    # Optimization
    "optimize",
    "run_optimization",
    "OptimizeConfig",
    "OptimizationResult",
    "ExperimentConfig",
    "ObjectiveReductionConfig",
    "ObjectiveReducer",
    "reduce_objectives",
    "run_self_check",
    # Problems - benchmark
    "ProblemSpec",
    "ProblemSelection",
    "available_problem_names",
    "make_problem_selection",
    "get_problem_names",
    "ZDT1",
    "ZDT2",
    "ZDT3",
    "ZDT4",
    "ZDT6",
    "DTLZ1",
    "DTLZ2",
    "DTLZ3",
    "DTLZ4",
    "WFG1",
    "WFG2",
    "WFG3",
    "WFG4",
    "WFG5",
    "WFG6",
    "WFG7",
    "WFG8",
    "WFG9",
    # Problems - real-world
    "FeatureSelectionProblem",
    "HyperparameterTuningProblem",
    "WeldedBeamDesignProblem",
    # Algorithms
    "NSGAII",
    "NSGAIIConfig",
    "NSGAIIConfigData",
    "MOEAD",
    "MOEADConfig",
    "MOEADConfigData",
    "SMSEMOA",
    "SMSEMOAConfig",
    "SMSEMOAConfigData",
    "NSGAIII",
    "NSGAIIIConfig",
    "NSGAIIIConfigData",
    "SPEA2",
    "SPEA2Config",
    "SPEA2ConfigData",
    "IBEA",
    "IBEAConfig",
    "IBEAConfigData",
    "SMPSO",
    "SMPSOConfig",
    "SMPSOConfigData",
    "available_algorithms",
    "resolve_algorithm",
    # Tuning
    "AlgorithmConfigSpace",
    "RandomSearchTuner",
    "RacingTuner",
    "ParamSpace",
    "Real",
    "Int",
    "Categorical",
    "Condition",
    "TuningTask",
    "EvalContext",
    "Instance",
    "Scenario",
    "build_nsgaii_config_space",
    "build_nsgaiii_config_space",
    "build_moead_config_space",
    "build_smsemoa_config_space",
    "build_spea2_config_space",
    "config_from_assignment",
    "build_ibea_config_space",
    "build_smpso_config_space",
    # Plotting
    "plot_pareto_front_2d",
    "plot_pareto_front_3d",
    "plot_parallel_coordinates",
    "plot_hv_convergence",
    # MCDM
    "MCDMResult",
    "weighted_sum_scores",
    "tchebycheff_scores",
    "reference_point_scores",
    "knee_point_scores",
    # Stats
    "FriedmanResult",
    "WilcoxonResult",
    "compute_ranks",
    "friedman_test",
    "pairwise_wilcoxon",
    "plot_critical_distance",
    # Exceptions
    "VAMOSError",
    "ConfigurationError",
    "InvalidAlgorithmError",
    "InvalidEngineError",
    "InvalidOperatorError",
    "MissingConfigError",
    "ProblemError",
    "InvalidProblemError",
    "ProblemDimensionError",
    "BoundsError",
    "OptimizationError",
    "ConvergenceError",
    "EvaluationError",
    "ConstraintViolationError",
    "DataError",
    "ResultsNotFoundError",
    "InvalidResultsError",
    "DependencyError",
    "BackendNotAvailableError",
]
