"""
VAMOS public API.

The symbols exported here are stable for end users. For advanced or
experimental work, import directly from the layered packages:
`vamos.foundation.*`, `vamos.engine.*`, `vamos.experiment.*`, `vamos.ux.*`.
"""

from .api import (
    ExperimentConfig,
    ObjectiveReductionConfig,
    ObjectiveReducer,
    OptimizeConfig,
    OptimizationResult,
    available_problem_names,
    make_problem_selection,
    optimize,
    run_self_check,
    reduce_objectives,
)
from .algorithms import (
    IBEA,
    IBEAConfig,
    IBEAConfigData,
    MOEAD,
    MOEADConfig,
    MOEADConfigData,
    NSGAII,
    NSGAIIConfig,
    NSGAIIConfigData,
    NSGAIII,
    NSGAIIIConfig,
    NSGAIIIConfigData,
    SMPSO,
    SMPSOConfig,
    SMPSOConfigData,
    SMSEMOA,
    SMSEMOAConfig,
    SMSEMOAConfigData,
    SPEA2,
    SPEA2Config,
    SPEA2ConfigData,
    available_algorithms,
    resolve_algorithm,
)
from .mcdm import (
    MCDMResult,
    knee_point_scores,
    reference_point_scores,
    tchebycheff_scores,
    weighted_sum_scores,
)
from .plotting import plot_hv_convergence, plot_parallel_coordinates, plot_pareto_front_2d, plot_pareto_front_3d
from .problems import (
    DTLZ1,
    DTLZ2,
    DTLZ3,
    DTLZ4,
    ProblemSelection,
    ProblemSpec,
    WFG1,
    ZDT1,
    ZDT2,
    ZDT3,
    ZDT4,
    ZDT6,
    get_problem_names,
)
from .stats import (
    FriedmanResult,
    WilcoxonResult,
    compute_ranks,
    friedman_test,
    pairwise_wilcoxon,
    plot_critical_distance,
)
from .tuning import (
    AlgorithmConfigSpace,
    BenchmarkReport,
    BenchmarkRunResult,
    BenchmarkSuite,
    ConfigInstanceSummary,
    ConfigSpec,
    ConfigSummary,
    MetaNSGAII,
    NSGAIITuner,
    RandomSearchTuner,
    TuningPipeline,
    build_ibea_config_space,
    build_moead_config_space,
    build_nsga3_config_space,
    build_nsgaii_config_space,
    build_smpso_config_space,
    build_smsemoa_config_space,
    build_spea2_config_space,
    compute_hyperparameter_importance,
    run_benchmark_suite,
    summarize_benchmark,
)

__all__ = [
    # Optimization
    "optimize",
    "OptimizeConfig",
    "OptimizationResult",
    "ExperimentConfig",
    "ObjectiveReductionConfig",
    "ObjectiveReducer",
    "reduce_objectives",
    "run_self_check",
    # Problems
    "ProblemSpec",
    "ProblemSelection",
    "available_problem_names",
    "make_problem_selection",
    "get_problem_names",
    "ZDT1",
    "ZDT2",
    "ZDT3",
    "ZDT4",
    "ZDT6",
    "DTLZ1",
    "DTLZ2",
    "DTLZ3",
    "DTLZ4",
    "WFG1",
    # Algorithms
    "NSGAII",
    "NSGAIIConfig",
    "NSGAIIConfigData",
    "MOEAD",
    "MOEADConfig",
    "MOEADConfigData",
    "SMSEMOA",
    "SMSEMOAConfig",
    "SMSEMOAConfigData",
    "NSGAIII",
    "NSGAIIIConfig",
    "NSGAIIIConfigData",
    "SPEA2",
    "SPEA2Config",
    "SPEA2ConfigData",
    "IBEA",
    "IBEAConfig",
    "IBEAConfigData",
    "SMPSO",
    "SMPSOConfig",
    "SMPSOConfigData",
    "available_algorithms",
    "resolve_algorithm",
    # Tuning
    "AlgorithmConfigSpace",
    "MetaNSGAII",
    "NSGAIITuner",
    "RandomSearchTuner",
    "TuningPipeline",
    "build_nsgaii_config_space",
    "build_nsga3_config_space",
    "build_moead_config_space",
    "build_smsemoa_config_space",
    "build_spea2_config_space",
    "build_ibea_config_space",
    "build_smpso_config_space",
    "compute_hyperparameter_importance",
    "BenchmarkSuite",
    "BenchmarkReport",
    "BenchmarkRunResult",
    "ConfigSpec",
    "ConfigSummary",
    "ConfigInstanceSummary",
    "run_benchmark_suite",
    "summarize_benchmark",
    # Plotting
    "plot_pareto_front_2d",
    "plot_pareto_front_3d",
    "plot_parallel_coordinates",
    "plot_hv_convergence",
    # MCDM
    "MCDMResult",
    "weighted_sum_scores",
    "tchebycheff_scores",
    "reference_point_scores",
    "knee_point_scores",
    # Stats
    "FriedmanResult",
    "WilcoxonResult",
    "compute_ranks",
    "friedman_test",
    "pairwise_wilcoxon",
    "plot_critical_distance",
]
