"""
Update per-algorithm runtime tables for the manuscript.

Generates a single merged table (frameworks_perf_variants.tex) with all algorithm
variants, included in `paper/manuscript/main.tex` via `\\input{...}`.

Usage:
  python paper/14_update_frameworks_perf_variant_tables_from_csv.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


ROOT_DIR = Path(__file__).parent.parent
DATA_DIR = ROOT_DIR / "experiments"
MANUSCRIPT_DIR = Path(__file__).parent / "manuscript"
GENERATED_TABLE_DIR = Path(__file__).parent / "generated" / "tables"
MAIN_TEX = MANUSCRIPT_DIR / "main.tex"


ALGO_SPECS = [
    ("nsgaii_ss", "NSGA-II (steady-state)", DATA_DIR / "benchmark_paper_nsgaii_ss.csv"),
    ("nsgaii_archive", "NSGA-II (ext. archive)", DATA_DIR / "benchmark_paper_nsgaii_archive.csv"),
    ("smsemoa", "SMS-EMOA", DATA_DIR / "benchmark_paper_smsemoa.csv"),
    ("moead", "MOEA/D", DATA_DIR / "benchmark_paper_moead.csv"),
]

MERGED_OUTPUT = GENERATED_TABLE_DIR / "frameworks_perf_variants.tex"
MERGED_LABEL = "tab:frameworks_perf_variants"
MERGED_CAPTION = "Median runtime (seconds) by problem family for algorithm variants"
MAIN_TABLE_CAPTION = "Median runtime (seconds) by problem family for NSGA-II variants, SMS-EMOA, and MOEA/D."


def _make_merged_table(sections: list[tuple[str, pd.DataFrame]], *, label: str, caption: str, generator: str) -> str:
    """Build a single merged table with an Algorithm column."""
    families = ["ZDT", "DTLZ", "WFG", "ZCAT"]

    lines = [
        f"% Auto-generated by {generator}",
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{ll" + "c" * (len(families) + 1) + "}",
        r"\toprule",
    ]

    header = " & ".join([f"\\textbf{{{f}}}" for f in families]) + " & \\textbf{Average}"
    lines.append(f"\\textbf{{Algorithm}} & \\textbf{{Framework}} & {header} \\\\")

    for idx, (section_name, family_df) in enumerate(sections):
        lines.append(r"\midrule")
        # Exclude frameworks with missing family aggregates from the merged
        # supplementary table to avoid mixing complete cross-family results
        # with partial additions (e.g., ZCAT-only appendices).
        display_df = family_df.loc[family_df[families].notna().all(axis=1)]
        sorted_fws = _sorted_frameworks(display_df.index.tolist())

        for i, fw in enumerate(sorted_fws):
            algo_cell = section_name if i == 0 else ""
            row = display_df.loc[fw]
            row_str = []
            for col in families + ["Average"]:
                val = float(row[col])
                col_min = float(display_df[col].min())
                if abs(val - col_min) < 1e-9:
                    row_str.append(f"\\textbf{{{val:.2f}}}")
                else:
                    row_str.append(f"{val:.2f}")
            lines.append(f"{algo_cell} & {fw} & {' & '.join(row_str)} \\\\")

    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def _algo_cell(display_name: str, row_idx: int) -> str:
    """Render algorithm label in 1-2 lines to match main.tex style."""
    if " (" in display_name and display_name.endswith(")"):
        head, tail = display_name.split(" (", 1)
        if row_idx == 0:
            return head
        if row_idx == 1:
            return f"({tail}"
        return ""
    return display_name if row_idx == 0 else ""


def _make_main_table(
    sections: list[tuple[str, pd.DataFrame]],
    *,
    label: str,
    caption: str,
) -> str:
    """Build the table format used directly in manuscript/main.tex."""
    families = ["ZDT", "DTLZ", "WFG", "ZCAT"]
    fw_order = ["VAMOS", "pymoo", "jMetalPy"]

    lines = [
        r"\begin{table}[htbp]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{ll" + "c" * len(families) + "}",
        r"\toprule",
        r"\textbf{Algorithm} & \textbf{Framework} & " + " & ".join([f"\\textbf{{{f}}}" for f in families]) + r" \\",
    ]

    for sec_idx, (display_name, family_df) in enumerate(sections):
        lines.append(r"\midrule")

        present_rows = [fw for fw in fw_order if fw in family_df.index]
        if not present_rows:
            continue

        col_mins: dict[str, float] = {}
        for fam in families:
            vals = [float(family_df.at[fw, fam]) for fw in present_rows if fam in family_df.columns and pd.notna(family_df.at[fw, fam])]
            col_mins[fam] = min(vals) if vals else float("nan")

        for i, fw in enumerate(present_rows):
            row = family_df.loc[fw]
            cells: list[str] = []
            for fam in families:
                val = row[fam] if fam in family_df.columns else float("nan")
                if pd.isna(val):
                    cells.append("---")
                else:
                    sval = f"{float(val):.2f}"
                    if pd.notna(col_mins[fam]) and abs(float(val) - col_mins[fam]) < 1e-9:
                        sval = f"\\textbf{{{sval}}}"
                    cells.append(sval)
            lines.append(f"{_algo_cell(display_name, i)} & {fw} & {' & '.join(cells)} \\\\")

    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def _find_table_bounds(content: str, label: str) -> tuple[int, int] | None:
    needle = f"\\label{{{label}}}"
    label_pos = content.find(needle)
    if label_pos < 0:
        return None
    begin_pos = content.rfind(r"\begin{table}", 0, label_pos)
    if begin_pos < 0:
        begin_pos = content.rfind(r"\begin{table*}", 0, label_pos)
    if begin_pos < 0:
        return None
    end_pos = content.find(r"\end{table}", label_pos)
    if end_pos < 0:
        end_pos = content.find(r"\end{table*}", label_pos)
        if end_pos < 0:
            return None
        end_pos += len(r"\end{table*}")
    else:
        end_pos += len(r"\end{table}")
    return begin_pos, end_pos


def _replace_table_in_tex(content: str, label: str, new_table: str) -> tuple[str, bool]:
    bounds = _find_table_bounds(content, label)
    if bounds is None:
        return content, False
    b, e = bounds
    return content[:b] + new_table + content[e:], True


def _get_family(problem_name: str) -> str:
    if problem_name.startswith("zdt"):
        return "ZDT"
    if problem_name.startswith("dtlz"):
        return "DTLZ"
    if problem_name.startswith("wfg"):
        return "WFG"
    if problem_name.startswith("zcat"):
        return "ZCAT"
    return "Other"


def _sorted_frameworks(frameworks: list[str]) -> list[str]:
    order_map = {"VAMOS": 0, "pymoo": 1, "jMetalPy": 2, "DEAP": 3, "Platypus": 4}

    def sort_key(name: str) -> int:
        for k, v in order_map.items():
            if k.lower() == name.lower():
                return v
            if k in name:
                return v
        return 99

    return sorted(frameworks, key=sort_key)


def _make_table(family_df: pd.DataFrame, *, label: str, caption: str, generator: str) -> str:
    families = [col for col in ["ZDT", "DTLZ", "WFG", "ZCAT"] if col in family_df.columns]
    caption = caption.strip()
    if caption.endswith("."):
        caption = caption[:-1]

    lines = [
        f"% Auto-generated by {generator}",
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{l" + "c" * len(families) + "c}",
        r"\toprule",
    ]

    header = " & ".join([f"\\textbf{{{f}}}" for f in families]) + " & \\textbf{Average}"
    lines.append(f"\\textbf{{Framework}} & {header} \\\\")
    lines.append(r"\midrule")

    for fw in _sorted_frameworks(family_df.index.tolist()):
        row = family_df.loc[fw]
        row_str = []
        for col in families + ["Average"]:
            val = float(row[col])
            col_min = float(family_df[col].min())
            if abs(val - col_min) < 1e-9:
                row_str.append(f"\\textbf{{{val:.2f}}}")
            else:
                row_str.append(f"{val:.2f}")
        lines.append(f"{fw} & {' & '.join(row_str)} \\\\")

    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def _load_family_table(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    if df.empty:
        raise SystemExit(f"No rows in CSV: {csv_path}")

    df["family"] = df["problem"].astype(str).apply(_get_family)
    # Family runtime protocol in the manuscript:
    # sum per family for each seed, then median across seeds.
    family_seed = df.groupby(["framework", "seed", "family"], as_index=False)["runtime_seconds"].sum()
    family = family_seed.groupby(["framework", "family"])["runtime_seconds"].median().unstack()

    # Keep only standard families; drop "Other" if present.
    family = family[[c for c in ["ZDT", "DTLZ", "WFG", "ZCAT"] if c in family.columns]]

    # Average across available families.
    family["Average"] = family.mean(axis=1)

    # Paper tables show only the tuned VAMOS implementation (prefer numba, fallback to moocore/numpy).
    vamos_rep = None
    for candidate in ("VAMOS (numba)", "VAMOS (moocore)", "VAMOS (numpy)"):
        if candidate in family.index:
            vamos_rep = candidate
            break
    if vamos_rep is not None:
        family = family.rename(index={vamos_rep: "VAMOS"})

    # Drop other VAMOS variants.
    family = family.loc[~family.index.to_series().astype(str).str.contains(r"^VAMOS \(", regex=True)]

    return family


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Regenerate the manuscript framework-variant table.")
    parser.add_argument("--overwrite", action="store_true", help="Replace an existing generated table.")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    if MERGED_OUTPUT.exists() and not args.overwrite:
        raise FileExistsError(f"Refusing to overwrite existing table: {MERGED_OUTPUT}. Pass --overwrite to replace it.")
    try:
        generator = Path(__file__).resolve().relative_to(ROOT_DIR).as_posix()
    except Exception:
        generator = Path(__file__).name

    sections: list[tuple[str, pd.DataFrame]] = []
    for algo_key, display_name, csv_path in ALGO_SPECS:
        if not csv_path.is_file():
            print(f"  [SKIP] {csv_path} not found")
            continue
        family_df = _load_family_table(csv_path)
        sections.append((display_name, family_df))
        print(f"  Loaded {algo_key}: {len(family_df)} frameworks")

    if not sections:
        raise SystemExit("No data loaded")

    latex = _make_merged_table(
        sections,
        label=MERGED_LABEL,
        caption=MERGED_CAPTION,
        generator=generator,
    )
    MERGED_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    MERGED_OUTPUT.write_text(latex, encoding="utf-8")
    print(f"Updated: {MERGED_OUTPUT}")

    if MAIN_TEX.is_file():
        main_table = _make_main_table(
            sections,
            label=MERGED_LABEL,
            caption=MAIN_TABLE_CAPTION,
        )
        content = MAIN_TEX.read_text(encoding="utf-8")
        content_new, replaced = _replace_table_in_tex(content, MERGED_LABEL, main_table)
        if replaced:
            MAIN_TEX.write_text(content_new, encoding="utf-8")
            print(f"Updated: {MAIN_TEX} ({MERGED_LABEL})")
        else:
            print(f"Warning: label {MERGED_LABEL} not found in {MAIN_TEX}")


if __name__ == "__main__":
    main()
