"""
Update per-algorithm runtime tables for the manuscript.

Generates a single merged table (frameworks_perf_variants.tex) with all algorithm
variants, included in `paper/manuscript/main.tex` via `\\input{...}`.

Usage:
  python paper/14_update_frameworks_perf_variant_tables_from_csv.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd


ROOT_DIR = Path(__file__).parent.parent
DATA_DIR = ROOT_DIR / "experiments"
MANUSCRIPT_DIR = Path(__file__).parent / "manuscript"


ALGO_SPECS = [
    ("nsgaii_ss", "NSGA-II (steady-state)", DATA_DIR / "benchmark_paper_nsgaii_ss.csv"),
    ("nsgaii_archive", "NSGA-II (ext. archive)", DATA_DIR / "benchmark_paper_nsgaii_archive.csv"),
    ("smsemoa", "SMS-EMOA", DATA_DIR / "benchmark_paper_smsemoa.csv"),
    ("moead", "MOEA/D", DATA_DIR / "benchmark_paper_moead.csv"),
]

MERGED_OUTPUT = MANUSCRIPT_DIR / "frameworks_perf_variants.tex"
MERGED_LABEL = "tab:frameworks_perf_variants"
MERGED_CAPTION = "Median runtime (seconds) by problem family for algorithm variants"


def _make_merged_table(sections: list[tuple[str, pd.DataFrame]], *, label: str, caption: str, generator: str) -> str:
    """Build a single merged table with multicolumn section headers."""
    families = ["ZDT", "DTLZ", "WFG"]
    n_cols = len(families) + 1  # +1 for Average

    lines = [
        f"% Auto-generated by {generator}",
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{l" + "c" * n_cols + "}",
        r"\toprule",
    ]

    header = " & ".join([f"\\textbf{{{f}}}" for f in families]) + " & \\textbf{Average}"
    lines.append(f"\\textbf{{Framework}} & {header} \\\\")

    for idx, (section_name, family_df) in enumerate(sections):
        lines.append(r"\midrule")
        lines.append(rf"\multicolumn{{{n_cols + 1}}}{{l}}{{\textit{{{section_name}}}}} \\")

        for fw in _sorted_frameworks(family_df.index.tolist()):
            row = family_df.loc[fw]
            row_str = []
            for col in families + ["Average"]:
                val = float(row[col])
                col_min = float(family_df[col].min())
                if abs(val - col_min) < 1e-9:
                    row_str.append(f"\\textbf{{{val:.2f}}}")
                else:
                    row_str.append(f"{val:.2f}")
            lines.append(f"{fw} & {' & '.join(row_str)} \\\\")

    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def _get_family(problem_name: str) -> str:
    if problem_name.startswith("zdt"):
        return "ZDT"
    if problem_name.startswith("dtlz"):
        return "DTLZ"
    if problem_name.startswith("wfg"):
        return "WFG"
    return "Other"


def _sorted_frameworks(frameworks: list[str]) -> list[str]:
    order_map = {"VAMOS": 0, "pymoo": 1, "jMetalPy": 2, "DEAP": 3, "Platypus": 4}

    def sort_key(name: str) -> int:
        for k, v in order_map.items():
            if k.lower() == name.lower():
                return v
            if k in name:
                return v
        return 99

    return sorted(frameworks, key=sort_key)


def _make_table(family_df: pd.DataFrame, *, label: str, caption: str, generator: str) -> str:
    families = [col for col in ["ZDT", "DTLZ", "WFG"] if col in family_df.columns]
    caption = caption.strip()
    if caption.endswith("."):
        caption = caption[:-1]

    lines = [
        f"% Auto-generated by {generator}",
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{l" + "c" * len(families) + "c}",
        r"\toprule",
    ]

    header = " & ".join([f"\\textbf{{{f}}}" for f in families]) + " & \\textbf{Average}"
    lines.append(f"\\textbf{{Framework}} & {header} \\\\")
    lines.append(r"\midrule")

    for fw in _sorted_frameworks(family_df.index.tolist()):
        row = family_df.loc[fw]
        row_str = []
        for col in families + ["Average"]:
            val = float(row[col])
            col_min = float(family_df[col].min())
            if abs(val - col_min) < 1e-9:
                row_str.append(f"\\textbf{{{val:.2f}}}")
            else:
                row_str.append(f"{val:.2f}")
        lines.append(f"{fw} & {' & '.join(row_str)} \\\\")

    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def _load_family_table(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    if df.empty:
        raise SystemExit(f"No rows in CSV: {csv_path}")

    df["family"] = df["problem"].astype(str).apply(_get_family)

    family = df.groupby(["framework", "family"])["runtime_seconds"].median().unstack()

    # Keep only standard families; drop "Other" if present.
    family = family[[c for c in ["ZDT", "DTLZ", "WFG"] if c in family.columns]]

    # Average across available families.
    family["Average"] = family.mean(axis=1)

    # Paper tables show only the tuned VAMOS implementation (prefer numba, fallback to moocore/numpy).
    vamos_rep = None
    for candidate in ("VAMOS (numba)", "VAMOS (moocore)", "VAMOS (numpy)"):
        if candidate in family.index:
            vamos_rep = candidate
            break
    if vamos_rep is not None:
        family = family.rename(index={vamos_rep: "VAMOS"})

    # Drop other VAMOS variants.
    family = family.loc[~family.index.to_series().astype(str).str.contains(r"^VAMOS \(", regex=True)]

    return family


def main() -> None:
    try:
        generator = Path(__file__).resolve().relative_to(ROOT_DIR).as_posix()
    except Exception:
        generator = Path(__file__).name

    sections: list[tuple[str, pd.DataFrame]] = []
    for algo_key, display_name, csv_path in ALGO_SPECS:
        if not csv_path.is_file():
            print(f"  [SKIP] {csv_path} not found")
            continue
        family_df = _load_family_table(csv_path)
        sections.append((display_name, family_df))
        print(f"  Loaded {algo_key}: {len(family_df)} frameworks")

    if not sections:
        raise SystemExit("No data loaded")

    latex = _make_merged_table(
        sections,
        label=MERGED_LABEL,
        caption=MERGED_CAPTION,
        generator=generator,
    )
    MERGED_OUTPUT.write_text(latex, encoding="utf-8")
    print(f"Updated: {MERGED_OUTPUT}")


if __name__ == "__main__":
    main()
