"""
Generate merged HV summary table for NSGA-II variants (steady-state and external archive).

Usage: python paper/17_update_variant_hv_tables_from_csv.py

Reads:
  - experiments/benchmark_paper_nsgaii_ss.csv
  - experiments/benchmark_paper_nsgaii_archive.csv

Writes:
  - paper/manuscript/frameworks_hv_variants.tex
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT_DIR = Path(__file__).parent.parent
DATA_DIR = ROOT_DIR / "experiments"
MANUSCRIPT_DIR = Path(__file__).parent / "manuscript"

# Map framework names to display names for HV tables (use Numba as representative VAMOS backend)
VAMOS_BACKEND = "VAMOS (numba)"

ALGO_SPECS = [
    ("nsgaii_ss", "NSGA-II (steady-state)", DATA_DIR / "benchmark_paper_nsgaii_ss.csv"),
    ("nsgaii_archive", "NSGA-II (ext. archive)", DATA_DIR / "benchmark_paper_nsgaii_archive.csv"),
]

MERGED_OUTPUT = MANUSCRIPT_DIR / "frameworks_hv_variants.tex"
MERGED_LABEL = "tab:frameworks_hv_variants"
MERGED_CAPTION = "Normalized hypervolume summary (median (IQR)) by problem family for NSGA-II variants"

# Framework display order (VAMOS first, then alphabetical competitors)
FRAMEWORK_ORDER = ["VAMOS", "pymoo", "jMetalPy", "DEAP", "Platypus"]


def get_family(problem: str) -> str:
    if problem.startswith("zdt"):
        return "ZDT"
    if problem.startswith("dtlz"):
        return "DTLZ"
    if problem.startswith("wfg"):
        return "WFG"
    if problem.startswith("zcat"):
        return "ZCAT"
    return "Other"


def _normalize_fw(fw: str) -> str:
    """Collapse VAMOS backend variants into a single 'VAMOS' label, keeping the Numba backend."""
    if fw.startswith("VAMOS"):
        return fw  # Keep backend label for filtering
    return fw


def build_hv_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Build a family-level HV summary: median (IQR) per framework per family."""
    # Keep only the primary VAMOS backend (prefer numba, fallback to moocore, then numpy)
    vamos_backend = VAMOS_BACKEND
    if vamos_backend not in df["framework"].values:
        for fallback in ("VAMOS (moocore)", "VAMOS (numpy)"):
            if fallback in df["framework"].values:
                vamos_backend = fallback
                break
    vamos_rows = df[df["framework"] == vamos_backend].copy()
    vamos_rows["framework"] = "VAMOS"
    other_rows = df[~df["framework"].str.startswith("VAMOS")].copy()
    df_clean = pd.concat([vamos_rows, other_rows], ignore_index=True)

    df_clean["family"] = df_clean["problem"].apply(get_family)

    # Compute per-problem median HV across seeds
    per_problem = (
        df_clean.groupby(["framework", "problem", "family"])["hypervolume"]
        .median()
        .reset_index()
        .rename(columns={"hypervolume": "hv_median"})
    )

    # Compute family-level summary: median and IQR of per-problem medians
    rows = []
    for fw in FRAMEWORK_ORDER:
        fw_data = per_problem[per_problem["framework"] == fw]
        if fw_data.empty:
            continue
        row = {"Framework": fw}
        for family in ["ZDT", "DTLZ", "WFG", "ZCAT"]:
            family_data = fw_data[fw_data["family"] == family]["hv_median"]
            if family_data.empty:
                row[family] = "---"
            else:
                med = family_data.median()
                iqr = family_data.quantile(0.75) - family_data.quantile(0.25)
                row[family] = f"{med:.3f} ({iqr:.3f})"
        # Overall: all per-problem medians
        all_medians = fw_data["hv_median"]
        med = all_medians.median()
        iqr = all_medians.quantile(0.75) - all_medians.quantile(0.25)
        row["Overall"] = f"{med:.3f} ({iqr:.3f})"
        rows.append(row)

    return pd.DataFrame(rows)


def make_merged_latex_table(sections: list[tuple[str, pd.DataFrame]], *, label: str, caption: str) -> str:
    """Generate a single table* spanning both columns with an Algorithm column."""
    families = [f for f in ["ZDT", "DTLZ", "WFG", "ZCAT"] if any(f in summary.columns for _, summary in sections)]
    n_cols = len(families) + 1  # +1 for Overall
    col_spec = "ll" + "c" * n_cols
    header_cells = " & ".join([rf"\textbf{{{f}}}" for f in families]) + r" & \textbf{Overall\textsuperscript{*}}"
    lines = [
        f"% Auto-generated by {Path(__file__).name}",
        "",
        r"\begin{table*}[htbp]",
        r"\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
        rf"\textbf{{Algorithm}} & \textbf{{Framework}} & {header_cells} \\",
    ]

    for section_name, summary in sections:
        lines.append(r"\midrule")
        for i, (_, row) in enumerate(summary.iterrows()):
            algo_cell = section_name if i == 0 else ""
            fw = row["Framework"]
            cells = [row.get(f, "---") for f in families] + [row.get("Overall", "---")]
            lines.append(f"{algo_cell} & {fw} & {' & '.join(str(c) for c in cells)} \\\\")

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
    ])

    return "\n".join(lines) + "\n"


def main() -> None:
    sections: list[tuple[str, pd.DataFrame]] = []
    for algo_key, display_name, csv_path in ALGO_SPECS:
        if not csv_path.exists():
            print(f"  [SKIP] {csv_path} not found")
            continue

        print(f"Processing {algo_key}...")
        df = pd.read_csv(csv_path)
        summary = build_hv_summary(df)
        sections.append((display_name, summary))
        print(summary.to_string(index=False))
        print()

    if not sections:
        raise SystemExit("No data loaded")

    latex = make_merged_latex_table(sections, label=MERGED_LABEL, caption=MERGED_CAPTION)
    MERGED_OUTPUT.write_text(latex, encoding="utf-8")
    print(f"Wrote {MERGED_OUTPUT}")


if __name__ == "__main__":
    main()
